### ISSUE TITLE
Not compatible with latest rider version

### ISSUE THREAD

**Issue by Gerolmed** [seclerp/rider-monogame#11]
![image](https://user-images.githubusercontent.com/19486712/165307791-f2ae9fc3-cd4f-4f60-8aac-a0b513c6ff2e.png)

**Comment by seclerp** [comment]
@Gerolmed `1.0.1` release with 2022.1 support is out, it will be available on Marketplace in a few days after approval

Temporarily you could install it from a .zip file from release page [here](https://github.com/seclerp/rider-monogame/releases/tag/v1.0.1)
