### ISSUE TITLE
Not compatible with 2022.2.1

### ISSUE THREAD

**Issue by matt-clegg** [seclerp/rider-monogame#12]
Will this plugin be made compatible with Rider 2022.2.1?

**Comment by seclerp** [comment]
It is:

![image](https://user-images.githubusercontent.com/20597871/184539901-b1d58901-d27f-4882-8c4b-cb7bb3d5c103.png)

Seems like you are using an old version of the plugin which is not.

**Comment by seclerp** [comment]
Thanks for the issue, it will be compatible in the nearest future with the service update.

**Comment by seclerp** [comment]
@matt-clegg a new version of the plugin was released with Rider 2022.2 support
