### ISSUE TITLE
Monogame 3.8.1 seems to have changed the install and launch process for mgcb-editor

### ISSUE THREAD

**Issue by BadRAM** [seclerp/rider-monogame#13]
I haven't been able to get mgcb-editor to launch from the terminal, so I may be doing something wrong myself, but this monogame.net answer suggests some part of the install/launch process has changed.

https://community.monogame.net/t/mgcb-editor-register-error/17783/2

**Comment by seclerp** [comment]
Thanks for letting me know! It's ridiculous they have this change in a patch-version update...

Will try to allocate some time to work on it.
