### ISSUE TITLE
General: refactor MGCB Editor Tool detection and installation logic

### ISSUE THREAD

**Issue by seclerp** [seclerp/rider-monogame#14]
Currently, MGCB Editor Tool is detected from the frontend side in quite an ineffective and buggy way.

ReSharper 2022.2 SDK comes with `NuGetDotnetToolsTracker` that could be used on a project-scoped level to detect `mgcb-editor` tool instance (both local and global ones).

We should also keep in mind that according to #13 MonoGame 3.8.1 has changed the way of installing and using `mgcb-editor` tool. It will be great if we come to a generic approach that could work on any MonoGame version without branching.

**Comment by ArkyonVeil** [comment]
Currently the only workaround that I found is going to the project directory and running dotnet mgcb-editor on the command line.
(An alternate, faster method exists by running dotnet mgcb-editor in the Rider's terminal.)

Though just being able to click a mgcb file and having it run would be nice.

**Comment by seclerp** [comment]
Detection should work now, installation feature was temporarily removed.
