### ISSUE TITLE
Error after trying to install MGCB Editor 

### ISSUE THREAD

**Issue by capsey** [seclerp/rider-monogame#15]
I clicked on "Install" option and got this cryptic error. I have plugin version 222.0.0 installed from Marketplace

![screenshot](https://user-images.githubusercontent.com/46106832/199774360-71cb6410-cf4d-4aab-89a3-6aec6db905ab.png)
![screenshot](https://user-images.githubusercontent.com/46106832/199774385-e81016db-f721-451f-8157-149c8bc94010.png)

**Comment by seclerp** [comment]
Hey @capsey, thanks for the report. This will be fixed by #14, but, unfortunately, I don't know when I will have time to implement it :(
But contributions are welcome!
