### ISSUE TITLE
Update to latest Rider version

### ISSUE THREAD

**Issue by EnergyNick** [seclerp/rider-monogame#16]
Hello!

Would it be possible to update the current version of the plugin to Rider 2023.1? 
At the moment it does not work completely due to compatibility with the latest builds

**Comment by seclerp** [comment]
Hi @EnergyNick, currently I don't have enough time capacity to bump all necessary versions and test, sorry :(

But any contributions are very welcome!

**Comment by seclerp** [comment]
Hi @EnergyNick, just want to let you know about the status - I'm currently working on the release for Rider 2023.1.
